import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is generated from the folder structure under developer/.
const sidebars: SidebarsConfig = {
  developerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
