import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is generated from the folder structure under user-docs/.
const sidebars: SidebarsConfig = {
  userSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
